name: Daily Commit Action

on:
  schedule:
    # Runs daily at 09:30 UTC
    - cron: "30 9 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add timestamp file – 21f3000697@ds.study.iitm.ac.in
        run: |
          echo "Commit at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit at $(date -u)"
          git push
